### ISSUE TITLE
[Error] (ACulinaryArtillery): Could not find transpiler anchor - Current state is invalid

### ISSUE THREAD

**Issue by Diometus** [l33tmaan/ACulinaryArtillery---.NET7#2]
VS Client version: 1.18.8-rc1
Mod version: A Culinary Artillery 1.0.12_RC_2.zip
Play-type: Multiplayer Server

Showing in client-main.txt:
"[Error] (ACulinaryArtillery): Could not find transpiler anchor - Current state is invalid"
Number of instances: 4

Zip contains the following:
client-main.txt
client-debug.txt
harmony-log.txt

[ACulinaryArtillery_transpiler anchor_Logs.zip](https://github.com/l33tmaan/ACulinaryArtillery---.NET7/files/12265404/ACulinaryArtillery_transpiler.anchor_Logs.zip)

**Comment by l33tmaan** [comment]
This should be resolved now!
