### ISSUE TITLE
Current Version Number is the same as previous version number.

### ISSUE THREAD

**Issue by Rivernoodl** [l33tmaan/ACulinaryArtillery---.NET7#3]
Players Updating from the .NET4 Version will have trouble because the .NET7 version number is the same.

Currently the remedy is to delete the old version from the mod folder before attempting to install the latest version.

**I recommend posting this fix on the main page, or changing the version number to be different so Vintage Story recognizes it as a different version.**

**Comment by l33tmaan** [comment]
I don't understand what the actual problem is. What trouble will people have?

**Comment by Rivernoodl** [comment]
Just based on my own experience, I went to update to the newest version and Vintage Craft says "This is the same version number, mod enabled instead of downloaded!"

This seems well and all, but this means Vintage Story erroneously reports v1.0.12 as being the same as v1.0.12-pre.2 and refuses to update to the newer version.  This means that after updating expanded foods from v1.6.6 to v1.6.7 (with A Culinary Artillery still on v1.0.12) the game will break and the player will have no idea why, as what happened to me this afternoon.

I think in order for vintage story to allow changing of the files to the .NET7 update organically, the version will have to be v1.0.13.

**Comment by l33tmaan** [comment]
I see, I believe other people have mentioned this to me before. I'll do that, thank you for the heads up!

**Comment by l33tmaan** [comment]
This should be fixed in the latest releases!
